feat(NET-554): add option to upgrade client version in hosts table
gravitl/netmaker-ui-2 pull request #220
Opened 2023-08-16 21:18 UTC by pwilson77

2023-08-17 10:58 UTC, Aceix requested changes

2023-08-17 10:58 UTC, Aceix commented on src/pages/hosts/HostsPage.tsx
> +                  Are you sure you want to upgrade the version of this host {host.name}?
is it possible to know the version user is upgrading to? would be helpful to show

2023-08-17 10:58 UTC, Aceix commented on src/pages/hosts/HostsPage.tsx
> +    [notify, store.nodes],
remove `store.nodes`

2023-08-17 10:58 UTC, Aceix commented on src/pages/hosts/HostsPage.tsx
> +                  },
on L414, add missing dependencies to the array 'confirmUpgradeClient', 'requestHostPull', and 'store.serverConfig?.Version'

2023-09-29 07:57 UTC, Aceix commented on src/pages/hosts/HostsPage.tsx
> +                  Are you sure you want to upgrade the version of this host {host.name}?
judging from the backend PR, it up/downgrades to the server version. so you can specify this in the ui as well

2023-10-02 11:01 UTC, pwilson77 commented on src/pages/hosts/HostsPage.tsx
> +                  Are you sure you want to upgrade the version of this host {host.name}?
if its upgrading / downgrading I guess I need to know the next version

2023-10-02 15:55 UTC, Aceix commented on src/pages/hosts/HostsPage.tsx
> +                  Are you sure you want to upgrade the version of this host {host.name}?
seen. actually, it only upgrades upto server version. let's specify the version then

2023-10-05 12:02 UTC, Aceix requested changes
pending 2 changes

2023-10-06 15:29 UTC, pwilson77 commented on src/pages/hosts/HostsPage.tsx
> +    [notify, store.nodes],
done

2023-10-06 15:30 UTC, pwilson77 commented on src/pages/hosts/HostsPage.tsx
> +                  },
done

2023-10-06 16:35 UTC, Aceix approved these changes

2023-10-06 16:38 UTC, merged