feat(NET-552): user management redesign
gravitl/netmaker-ui-2 pull request #228
Opened 2023-08-24 02:25 UTC by pwilson77

2023-08-25 11:08 UTC, Aceix requested changes

2023-08-25 11:08 UTC, Aceix commented on src/models/User.ts
> +  [key: string]: object;
can the types be more specific

```suggestion
  [key: Node['id']]: User;  // maybe User is wrong, but use a more specific type instead of object
```

2023-08-25 11:08 UTC, Aceix commented on src/pages/networks/NetworkDetailsPage.tsx
> +                              <UserOutlined /> Add / Remove Users
an icon here may look odd. maybe add to the rest or remove?

2023-08-25 13:41 UTC, pwilson77 commented on src/components/modals/add-user-modal/AddUserModal.tsx
>                    form.setFieldValue('networks', []);
I guess you are talking about the onchange right?

2023-08-25 13:42 UTC, pwilson77 commented on src/components/modals/transfer-super-admin-rights/TransferSuperAdminRightsModal.tsx
> +      setAdmins(users.filter((user) => user.isadmin));
I don't think the comment is needed, so removed it

2023-08-25 13:56 UTC, pwilson77 commented on src/pages/networks/NetworkDetailsPage.tsx
> +                              <UserOutlined /> Add / Remove Users
oh the rest have icons, check above

2023-08-29 08:58 UTC, Aceix approved these changes

2023-08-31 19:51 UTC, theguy951357 approved these changes

2023-09-01 15:43 UTC, merged