feat(NET-592): allow generic DNS entries
gravitl/netmaker-ui-2 pull request #260
Opened 2023-09-11 11:55 UTC by pwilson77

2023-09-12 12:03 UTC, Aceix requested changes
changes are good other than an unused function param

2023-09-12 12:03 UTC, Aceix commented on src/components/modals/add-dns-modal/AddDnsModal.tsx
> +  const validateUrl = (_: any, value: string, callback: any) => {
remove unused parameter "callback"

2023-09-20 12:15 UTC, pwilson77 commented on src/components/modals/add-dns-modal/AddDnsModal.tsx
> +  const validateUrl = (_: any, value: string, callback: any) => {
fixed

2023-09-20 12:17 UTC, Aceix approved these changes

2023-09-20 12:20 UTC, merged