E2e scafolding
gravitl/netmaker-ui-2 pull request #364
Opened 2023-12-01 17:29 UTC by NEETweeb

some e2e scafolding

2023-12-01 17:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gravitl/netmaker-ui-2?pullRequest=364) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gravitl/netmaker-ui-2?pullRequest=364) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gravitl/netmaker-ui-2?pullRequest=364) it.</sub>

2023-12-04 12:59 UTC, Aceix requested changes
fix breaking pr test

2023-12-05 09:57 UTC, NEETweeb commented
Hello @Aceix, sir!
The errors can be ignored. That is how 'tests' are declared in Playwright :).

2023-12-05 10:24 UTC, NEETweeb commented
@Aceix It appears that there's conflict with Playwright lib and Vite lib in this case. Both have 'test'.
Playwright's 'test' can be implemented even without the 'declare'. While Vite's 'test' has to be inside Vite's 'declare'.

2023-12-05 10:40 UTC, Aceix commented on package.json
> +    "dotenv": "^16.3.1",
install as dev dependency

2023-12-05 11:31 UTC, Aceix commented
> @Aceix It appears that there's conflict with Playwright lib and Vite's lib. In this case, both have 'test'. Playwright's 'test' doesn't need 'declare'. While Vite's 'test' has to be implemented inside Vite's 'declare'.

okay. we'll have to find a way to ignore playwrite from vite then

2023-12-06 23:03 UTC, Aceix approved these changes

2023-12-06 23:04 UTC, merged