Static / Dynamic Nodes
gravitl/netmaker-ui-2 pull request #835
Opened 2024-10-21 11:53 UTC by imadtassaoui

2024-10-21 11:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gravitl/netmaker-ui-2?pullRequest=835) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gravitl/netmaker-ui-2?pullRequest=835) before we can accept your contribution.<br/><hr/>**Imad Tassaoui** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gravitl/netmaker-ui-2?pullRequest=835) it.</sub>

2024-10-22 09:50 UTC, Aceix requested changes
![image](https://github.com/user-attachments/assets/31504389-aca0-41b5-b29d-f3948fc59249)

increase the z-index of the popover. should be over the buttons

2024-10-22 09:50 UTC, Aceix commented on package.json
> -    "rc-virtual-list": "^3.14.5",
why are we removing this? i think it was used somewhere in a virtual table/list component

2024-10-22 09:50 UTC, Aceix commented on src/components/modals/add-node-modal/AddNodeDialog.tsx
> +    const baseUrl = 'https://fileserver.netmaker.io/releases/download/v0.25.0';
let's put all links in the constant file

2024-10-22 09:50 UTC, Aceix commented on src/components/modals/add-node-modal/AddNodeDialog.tsx
> +    const baseUrl = 'https://fileserver.netmaker.io/releases/download/v0.25.0';
change to `https://fileserver.netmaker.io/releases/download/${store.serverConfig?.Version}`

2024-10-22 09:50 UTC, Aceix commented on src/components/modals/add-node-modal/AddNodeDialog.tsx
> +  const getDownloadLink = (instruction: any, selectedVersion: string) => {
make this a useCallback else it'll cause unnecessary re-renders in L160's useEffect

2024-10-22 09:50 UTC, Aceix commented on src/components/modals/add-node-modal/AddNodeDialog.tsx
> +      </Link>
would it be better to rather open in the same tab?

2024-10-22 12:08 UTC, imadtassaoui commented on package.json
> -    "rc-virtual-list": "^3.14.5",
I think it's still there just got reordered somehow

2024-10-22 12:53 UTC, Aceix approved these changes

2024-10-29 13:43 UTC, merged